name: ci
on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          configFile: ./.devcontainer/symfony/devcontainer.json
          push: never
          # Change this to be your CI task/script
          runCmd: git config --global --add safe.directory /workspace && composer install --no-dev && phpstan analyse --level 3 src && phpcs --standard=PSR12 src